/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.myapp;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.MongoClient;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author Acer
 */
public class Editpas extends javax.swing.JFrame {
  DBCollection table;
    DB db;
    String []messageString={};
  
   public Editpas() {
        initComponents();
        BasicDBObject document =  new  BasicDBObject();
         
             MongoClient mongo ;
        try {
            mongo = new MongoClient("localhost", 27017); 
            db = mongo.getDB("mini");
           table=db.getCollection("passenger");
           
        } catch (UnknownHostException ex) {
            Logger.getLogger(รวมม.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        t = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        nn = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\31483830_1787911097933017_396862073436372992_n.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel8.setText("Count");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 98, -1));

        jLabel5.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel5.setText("Tel");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 98, -1));

        jLabel6.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel6.setText("Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 98, -1));

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jButton2.setText("Done");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 580, 130, -1));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 580, 129, -1));

        jLabel9.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel9.setText("Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 98, -1));
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 360, 45));
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 360, 45));
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 360, 45));
        getContentPane().add(nn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 360, 40));

        jButton3.setBackground(new java.awt.Color(51, 102, 255));
        jButton3.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(813, 150, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\31655709_1787938391263621_5393480442663927808_n.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Expas ex = new  Expas();
        ex.show();
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         BasicDBObject document =  new  BasicDBObject();
             MongoClient mongo ;
        try {
            mongo = new MongoClient("localhost", 27017); 
            db = mongo.getDB("mini");
           table=db.getCollection("passenger");
        } catch (UnknownHostException ex) {
            Logger.getLogger(Repas.class.getName()).log(Level.SEVERE, null, ex);
        }
        if( n.getText().isEmpty() && t.getText().isEmpty() && c.getText().isEmpty()){
             JOptionPane.showMessageDialog(null,"โปรดกรอกข้อมูล");
        }else if( n.getText().isEmpty() || t.getText().isEmpty() || c.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"โปรดกรอกข้อมูลให้ครบ");
    } else{
              BasicDBObject updateDocument = new BasicDBObject();
	  BasicDBObject searchQuery2 = new BasicDBObject().append("Name", nn.getText());
             updateDocument.append("$set", new BasicDBObject().append("Name", n.getText()).append("Tel", t.getText()).append("Count",Integer.parseInt(c.getText())));
          
	  table.updateMulti(searchQuery2, updateDocument);
           JOptionPane.showMessageDialog(this, "Updated");
            Expas ex = new  Expas();
           ex.show();
           this.hide();
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        BasicDBObject search = new BasicDBObject(); 
        search.put("Name", nn.getText());

    DBCursor cursor = table.find(search);
      
                String Row = cursor.next().toString();
                JSONObject obj = new JSONObject(Row);
                System.out.println(Row);
                  String Username = obj.getString("Name");
                System.out.println("Name: " + Username);
                
              
                 n.setText(obj.getString("Name"));  
                 t.setText(obj.getString("Tel"));
                  c.setText(obj.getInt("Count")+"");
                  
                
                
    }//GEN-LAST:event_jButton3ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editpas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editpas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editpas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editpas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editpas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField n;
    private javax.swing.JTextField nn;
    private javax.swing.JTextField t;
    // End of variables declaration//GEN-END:variables
}
