/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.myapp;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.MongoClient;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;

/**
 *
 * @author Acer
 */
public class redriver extends javax.swing.JFrame {

    DBCollection table;
    DB db;
    DefaultTableModel model;

    public redriver() {
        initComponents();
        pp1.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lp1 = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lc1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cp1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        pp = new javax.swing.JLabel();
        u1 = new javax.swing.JTextField();
        sttt = new javax.swing.JLabel();
        pp2 = new javax.swing.JRadioButton();
        pp1 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        cp = new javax.swing.JPasswordField();
        p1 = new javax.swing.JPasswordField();
        ln = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        lp = new javax.swing.JTextField();
        lc = new javax.swing.JTextField();
        pv = new javax.swing.JTextField();
        stt = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        dt = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        sdt = new javax.swing.JTextField();
        pk = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 220, 35));

        jButton3.setBackground(new java.awt.Color(51, 102, 255));
        jButton3.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jButton3.setText("Passenger");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 220, 35));

        jButton4.setBackground(new java.awt.Color(51, 102, 255));
        jButton4.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jButton4.setText("Driver ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 220, 35));

        jLabel3.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel4.setText("First Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel5.setText("Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        lp1.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        lp1.setText("License Plate");
        getContentPane().add(lp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        id1.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        id1.setText("ID Card");
        getContentPane().add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel8.setText("Status");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, -1, -1));

        jLabel9.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel9.setText("Subdistrict");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 100, -1));

        lc1.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        lc1.setText("License");
        getContentPane().add(lc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 80, -1));

        jLabel11.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel11.setText("Province");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 80, -1));

        jLabel12.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel12.setText("District");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 80, -1));

        jLabel13.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel13.setText("Parking");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 80, -1));

        cp1.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        cp1.setText("Confirm Password");
        getContentPane().add(cp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 157, -1));

        jButton5.setBackground(new java.awt.Color(51, 102, 255));
        jButton5.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, 162, -1));

        jLabel15.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel15.setText("Username");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 106, -1));

        pp.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        pp.setText("Password");
        getContentPane().add(pp, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 106, -1));

        u1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u1ActionPerformed(evt);
            }
        });
        getContentPane().add(u1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 365, 36));

        sttt.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        sttt.setText("Motorcycle Type");
        getContentPane().add(sttt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, -1, -1));

        pp2.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        pp2.setText("Public");
        pp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp2ActionPerformed(evt);
            }
        });
        getContentPane().add(pp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, -1, -1));

        pp1.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        pp1.setText("Private");
        pp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp1ActionPerformed(evt);
            }
        });
        getContentPane().add(pp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, -1));

        jButton6.setBackground(new java.awt.Color(51, 102, 255));
        jButton6.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jButton6.setText("Done");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 162, -1));
        getContentPane().add(cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 303, 365, 34));

        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 214, 365, 34));

        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        getContentPane().add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 230, 40));

        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });
        getContentPane().add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 230, 40));

        lp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lpActionPerformed(evt);
            }
        });
        getContentPane().add(lp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 230, 40));

        lc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcActionPerformed(evt);
            }
        });
        getContentPane().add(lc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 230, 40));

        pv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pvActionPerformed(evt);
            }
        });
        getContentPane().add(pv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 230, 40));

        stt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sttActionPerformed(evt);
            }
        });
        getContentPane().add(stt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 600, 230, 40));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 230, 40));

        dt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtActionPerformed(evt);
            }
        });
        getContentPane().add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 230, 40));

        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 230, 40));

        sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdtActionPerformed(evt);
            }
        });
        getContentPane().add(sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 230, 40));

        pk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pkActionPerformed(evt);
            }
        });
        getContentPane().add(pk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 230, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\31492493_1787938377930289_6823262308039393280_n.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        f.setText(null);
        ln.setText(null);
        n.setText(null);
        id.setText(null);
        lp.setText(null);
        lc.setText(null);
        pv.setText(null);
        dt.setText(null);
        sdt.setText(null);
        pk.setText(null);
        stt.setText(null);
        u1.setText(null);
        p1.setText(null);
        cp.setText(null);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void u1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        BasicDBObject document = new BasicDBObject();
        MongoClient mongo;
         //เชื่อมฐานข้อมูล
        try {
            mongo = new MongoClient("localhost", 27017);
            db = mongo.getDB("mini");
            table = db.getCollection("users");
            
            //เช็ค Username กับ เลข ปชช ซ้ำ
            document.put("Username", u1.getText()); 
             document.put("ID CARD", id.getText()); 
            BasicDBObject searchQuery = new BasicDBObject();
            searchQuery.put("Username", u1.getText());
            int c = table.find(searchQuery).count();
            if(c>0){
                    JOptionPane.showMessageDialog(this, "Username ซ้ำ");
                      return;
                }
            searchQuery = new BasicDBObject();
            searchQuery.put("ID CARD", id.getText());
            c = table.find(searchQuery).count();
            if(c>0){
                     JOptionPane.showMessageDialog(this, "ID CARD ซ้ำ");
                      return;
                }
             
        } catch (UnknownHostException ex) {
            Logger.getLogger(รวมม.class.getName()).log(Level.SEVERE, null, ex);
        }
       
                    
                if (id.getText().length() != 13) {
            JOptionPane.showMessageDialog(this, "กรุณากรอกเลขบัตรประชาชน 13 หลัก");
            id1.requestFocus();
            return;
        } else if (lc.getText().length() != 8) {
            JOptionPane.showMessageDialog(this, "กรุณากรอกเลขใบอนุญาตขับขี่ 8 หลัก");
            lc1.requestFocus();
            return;
        }else if (p1.getPassword().length != 6) {
            JOptionPane.showMessageDialog(this, "กรุณากรอกรหัสผ่านให้ครบ 6 ตัว");
            pp1.requestFocus();
            return;
        }else if (cp.getPassword().length != 6) {
            JOptionPane.showMessageDialog(this, "กรุณากรอกรหัสผ่านให้ครบ 6 ตัว");
            cp1.requestFocus();
            return;
            //เช็คว่าใส่ข้อมูลครบทุกช่องไหม
        } else if (id.getText().isEmpty() && ln.getText().isEmpty() && n.getText().isEmpty() && id.getText().isEmpty() && lp.getText().isEmpty() && lc.getText().isEmpty() && pv.getText().isEmpty() && dt.getText().isEmpty() && sdt.getText().isEmpty() && pk.getText().isEmpty() && stt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "โปรดกรอกข้อมูล");
        } else if (id.getText().isEmpty() || ln.getText().isEmpty() || n.getText().isEmpty() || id.getText().isEmpty() || lp.getText().isEmpty() || lc.getText().isEmpty() || pv.getText().isEmpty() || dt.getText().isEmpty() || sdt.getText().isEmpty() || pk.getText().isEmpty() || stt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "โปรดกรอกข้อมูลให้ครบ");
        } //เช็คว่ากดPrivate หรือ Public
        else if (pp1.isSelected()) {
                document.put("CarType", pp1.getText());
            } else {
                document.put("CarType", pp2.getText());
            }
            if (pp1.equals("Private")) {
                pp1.setSelected(true);

                document.put("Private", pp1.getText());
            } else if (pp2.equals("Public")) {
                pp2.setSelected(true);
                document.put("Public", pp2.getText());
                
                //เช็ครหัสกับconfirmว่าใส่ตรงกันไหม
            } else if(cp.getText().equals(p1.getText())){
                
                //ใส่ข้อมูลตามบล็อคเพื่อบันทึกลงฐานข้อมูล
            document.put("First Name", f.getText());
            document.put("Last Name", ln.getText());
            document.put("Number", n.getText());
            document.put("ID CARD", id.getText());
            document.put("License Plate", lp.getText());
            document.put("License", lc.getText());
            document.put("Province", pv.getText());
            document.put("District", dt.getText());
            document.put("SubDistrict", sdt.getText());
            document.put("Parking", pk.getText());
            document.put("on/off", stt.getText());
            document.put("Username", u1.getText());
            document.put("Password", p1.getText());
            document.put("Confirm Password", cp.getText());
            document.put("Status", "Driver");
                table.insert(document);
                JOptionPane.showMessageDialog(null, "Success!!!");
                 
                //เมื่อกด Done แล้ว ข้อมูลที่ใส่ตามบล็อคจะเคลียออกหมด
                f.setText(null);
            ln.setText(null);
            n.setText(null);
            id.setText(null);
            lp.setText(null);
            lc.setText(null);
            pv.setText(null);
            dt.setText(null);
            sdt.setText(null);
            pk.setText(null);
            stt.setText(null);
            u1.setText(null);
            p1.setText(null);
            cp.setText(null);
            }else{
                  JOptionPane.showMessageDialog(null, "กรอกรหัสไม่ตรงกัน");

            
                
                
            }

        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Home h = new Home();
        h.show();
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        redriver rd = new redriver();
        rd.show();
        this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Repas rp = new Repas();
        rp.show();
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp1ActionPerformed
        BasicDBObject document = new BasicDBObject();
        if (pp1.isSelected()) {
            pp2.setSelected(false);
        }
        document.put("Private", pp1.getText());


    }//GEN-LAST:event_pp1ActionPerformed

    private void pp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp2ActionPerformed
        BasicDBObject document = new BasicDBObject();
        if (pp2.isSelected()) {
            pp1.setSelected(false);
        }
        document.put("Private", pp2.getText());
    }//GEN-LAST:event_pp2ActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fActionPerformed

    private void lpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lpActionPerformed

    private void lcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lcActionPerformed

    private void pvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pvActionPerformed

    private void sttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sttActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void dtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdtActionPerformed

    private void pkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pkActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(redriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(redriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(redriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(redriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new redriver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cp;
    private javax.swing.JLabel cp1;
    private javax.swing.JTextField dt;
    private javax.swing.JTextField f;
    private javax.swing.JTextField id;
    private javax.swing.JLabel id1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lc;
    private javax.swing.JLabel lc1;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField lp;
    private javax.swing.JLabel lp1;
    private javax.swing.JTextField n;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField pk;
    private javax.swing.JLabel pp;
    private javax.swing.JRadioButton pp1;
    private javax.swing.JRadioButton pp2;
    private javax.swing.JTextField pv;
    private javax.swing.JTextField sdt;
    private javax.swing.JTextField stt;
    private javax.swing.JLabel sttt;
    private javax.swing.JTextField u1;
    // End of variables declaration//GEN-END:variables
}
